
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "C:/vcpkg/scripts/buildsystems/vcpkg.cmake:309 (find_program)"
      - "C:/Program Files/CMake/share/cmake-4.2/Modules/CMakeDetermineSystem.cmake:146 (include)"
      - "CMakeLists.txt:22 (project)"
    mode: "program"
    variable: "Z_VCPKG_CL"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "cl"
    candidate_directories:
      - "C:/Users/allen/.codex/tmp/arg0/codex-arg0VHd2pK/"
      - "C:/Program Files (x86)/Common Files/Oracle/Java/java8path/"
      - "C:/Program Files (x86)/Common Files/Oracle/Java/javapath/"
      - "C:/Windows/System32/"
      - "C:/Windows/"
      - "C:/Windows/System32/wbem/"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/"
      - "C:/Windows/System32/OpenSSH/"
      - "C:/Program Files/dotnet/"
      - "C:/Program Files/Git/cmd/"
      - "C:/Program Files/CMake/bin/"
      - "C:/Program Files/Microsoft SQL Server/170/Tools/Binn/"
      - "C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/"
      - "C:/Program Files/nodejs/"
      - "C:/Program Files/Docker/Docker/resources/bin/"
      - "C:/Program Files (x86)/Go/bin/"
      - "C:/Users/allen/AppData/Local/Programs/cursor/resources/app/codeBin/"
      - "C:/Users/allen/AppData/Local/Microsoft/WindowsApps/"
      - "C:/Users/allen/AppData/Local/Programs/cursor/resources/app/bin/"
      - "C:/Users/allen/.dotnet/tools/"
      - "C:/Users/allen/AppData/Local/GitHubDesktop/bin/"
      - "C:/Users/allen/AppData/Roaming/npm/"
      - "C:/Users/allen/AppData/Local/Programs/Microsoft VS Code/bin/"
      - "C:/Users/allen/AppData/Local/Programs/Antigravity/bin/"
      - "C:/Users/allen/go/bin/"
      - "C:/Users/allen/AppData/Local/OpenAI/Codex/bin/"
      - "C:/Program Files/WindowsApps/OpenAI.Codex_26.313.5234.0_x64__2p2nqsd0c76g0/app/resources/"
    searched_directories:
      - "C:/Users/allen/.codex/tmp/arg0/codex-arg0VHd2pK/cl.com"
      - "C:/Users/allen/.codex/tmp/arg0/codex-arg0VHd2pK/cl.exe"
      - "C:/Users/allen/.codex/tmp/arg0/codex-arg0VHd2pK/cl"
      - "C:/Program Files (x86)/Common Files/Oracle/Java/java8path/cl.com"
      - "C:/Program Files (x86)/Common Files/Oracle/Java/java8path/cl.exe"
      - "C:/Program Files (x86)/Common Files/Oracle/Java/java8path/cl"
      - "C:/Program Files (x86)/Common Files/Oracle/Java/javapath/cl.com"
      - "C:/Program Files (x86)/Common Files/Oracle/Java/javapath/cl.exe"
      - "C:/Program Files (x86)/Common Files/Oracle/Java/javapath/cl"
      - "C:/Windows/System32/cl.com"
      - "C:/Windows/System32/cl.exe"
      - "C:/Windows/System32/cl"
      - "C:/Windows/cl.com"
      - "C:/Windows/cl.exe"
      - "C:/Windows/cl"
      - "C:/Windows/System32/wbem/cl.com"
      - "C:/Windows/System32/wbem/cl.exe"
      - "C:/Windows/System32/wbem/cl"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/cl.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/cl.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/cl"
      - "C:/Windows/System32/OpenSSH/cl.com"
      - "C:/Windows/System32/OpenSSH/cl.exe"
      - "C:/Windows/System32/OpenSSH/cl"
      - "C:/Program Files/dotnet/cl.com"
      - "C:/Program Files/dotnet/cl.exe"
      - "C:/Program Files/dotnet/cl"
      - "C:/Program Files/Git/cmd/cl.com"
      - "C:/Program Files/Git/cmd/cl.exe"
      - "C:/Program Files/Git/cmd/cl"
      - "C:/Program Files/CMake/bin/cl.com"
      - "C:/Program Files/CMake/bin/cl.exe"
      - "C:/Program Files/CMake/bin/cl"
      - "C:/Program Files/Microsoft SQL Server/170/Tools/Binn/cl.com"
      - "C:/Program Files/Microsoft SQL Server/170/Tools/Binn/cl.exe"
      - "C:/Program Files/Microsoft SQL Server/170/Tools/Binn/cl"
      - "C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/cl.com"
      - "C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/cl.exe"
      - "C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/cl"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/cl.com"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/cl.exe"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/cl"
      - "C:/Program Files/nodejs/cl.com"
      - "C:/Program Files/nodejs/cl.exe"
      - "C:/Program Files/nodejs/cl"
      - "C:/Program Files/Docker/Docker/resources/bin/cl.com"
      - "C:/Program Files/Docker/Docker/resources/bin/cl.exe"
      - "C:/Program Files/Docker/Docker/resources/bin/cl"
      - "C:/Program Files (x86)/Go/bin/cl.com"
      - "C:/Program Files (x86)/Go/bin/cl.exe"
      - "C:/Program Files (x86)/Go/bin/cl"
      - "C:/Users/allen/AppData/Local/Programs/cursor/resources/app/codeBin/cl.com"
      - "C:/Users/allen/AppData/Local/Programs/cursor/resources/app/codeBin/cl.exe"
      - "C:/Users/allen/AppData/Local/Programs/cursor/resources/app/codeBin/cl"
      - "C:/Users/allen/AppData/Local/Microsoft/WindowsApps/cl.com"
      - "C:/Users/allen/AppData/Local/Microsoft/WindowsApps/cl.exe"
      - "C:/Users/allen/AppData/Local/Microsoft/WindowsApps/cl"
      - "C:/Users/allen/AppData/Local/Programs/cursor/resources/app/bin/cl.com"
      - "C:/Users/allen/AppData/Local/Programs/cursor/resources/app/bin/cl.exe"
      - "C:/Users/allen/AppData/Local/Programs/cursor/resources/app/bin/cl"
      - "C:/Users/allen/.dotnet/tools/cl.com"
      - "C:/Users/allen/.dotnet/tools/cl.exe"
      - "C:/Users/allen/.dotnet/tools/cl"
      - "C:/Users/allen/AppData/Local/GitHubDesktop/bin/cl.com"
      - "C:/Users/allen/AppData/Local/GitHubDesktop/bin/cl.exe"
      - "C:/Users/allen/AppData/Local/GitHubDesktop/bin/cl"
      - "C:/Users/allen/AppData/Roaming/npm/cl.com"
      - "C:/Users/allen/AppData/Roaming/npm/cl.exe"
      - "C:/Users/allen/AppData/Roaming/npm/cl"
      - "C:/Users/allen/AppData/Local/Programs/Microsoft VS Code/bin/cl.com"
      - "C:/Users/allen/AppData/Local/Programs/Microsoft VS Code/bin/cl.exe"
      - "C:/Users/allen/AppData/Local/Programs/Microsoft VS Code/bin/cl"
      - "C:/Users/allen/AppData/Local/Programs/Antigravity/bin/cl.com"
      - "C:/Users/allen/AppData/Local/Programs/Antigravity/bin/cl.exe"
      - "C:/Users/allen/AppData/Local/Programs/Antigravity/bin/cl"
      - "C:/Users/allen/go/bin/cl.com"
      - "C:/Users/allen/go/bin/cl.exe"
      - "C:/Users/allen/go/bin/cl"
      - "C:/Users/allen/AppData/Local/OpenAI/Codex/bin/cl.com"
      - "C:/Users/allen/AppData/Local/OpenAI/Codex/bin/cl.exe"
      - "C:/Users/allen/AppData/Local/OpenAI/Codex/bin/cl"
      - "C:/Program Files/WindowsApps/OpenAI.Codex_26.313.5234.0_x64__2p2nqsd0c76g0/app/resources/cl.com"
      - "C:/Program Files/WindowsApps/OpenAI.Codex_26.313.5234.0_x64__2p2nqsd0c76g0/app/resources/cl.exe"
      - "C:/Program Files/WindowsApps/OpenAI.Codex_26.313.5234.0_x64__2p2nqsd0c76g0/app/resources/cl"
    found: false
    search_context:
      ENV{PATH}:
        - "C:\\Users\\allen\\.codex\\tmp\\arg0\\codex-arg0VHd2pK"
        - "C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\java8path"
        - "C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath"
        - "C:\\WINDOWS\\system32"
        - "C:\\WINDOWS"
        - "C:\\WINDOWS\\System32\\Wbem"
        - "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\WINDOWS\\System32\\OpenSSH\\"
        - "C:\\Program Files\\dotnet\\"
        - "C:\\Program Files\\Git\\cmd"
        - "C:\\Program Files\\CMake\\bin"
        - "C:\\Program Files\\Microsoft SQL Server\\170\\Tools\\Binn\\"
        - "C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\170\\Tools\\Binn\\"
        - "C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit\\"
        - "C:\\Program Files\\nodejs\\"
        - "C:\\Program Files\\Docker\\Docker\\resources\\bin"
        - "C:\\Program Files (x86)\\Go\\bin"
        - "c:\\Users\\allen\\AppData\\Local\\Programs\\cursor\\resources\\app\\codeBin"
        - "C:\\Users\\allen\\AppData\\Local\\Microsoft\\WindowsApps"
        - "C:\\Users\\allen\\AppData\\Local\\Programs\\cursor\\resources\\app\\bin"
        - "C:\\Users\\allen\\.dotnet\\tools"
        - "C:\\Users\\allen\\AppData\\Local\\GitHubDesktop\\bin"
        - "C:\\Users\\allen\\AppData\\Roaming\\npm"
        - "C:\\Users\\allen\\AppData\\Local\\Programs\\Microsoft VS Code\\bin"
        - "C:\\Users\\allen\\AppData\\Local\\Programs\\Antigravity\\bin"
        - "C:\\Users\\allen\\go\\bin"
        - "C:\\Users\\allen\\AppData\\Local\\OpenAI\\Codex\\bin"
        - "C:\\Program Files\\WindowsApps\\OpenAI.Codex_26.313.5234.0_x64__2p2nqsd0c76g0\\app\\resources"
